# Generated by Django 4.0.3 on 2022-04-05 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Post date'),
        ),
    ]
