# Generated by Django 4.0.3 on 2022-04-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('blog', '0004_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPage',
            new_name='Post',
        ),
    ]
